/**:
  controller_manager:
    ros__parameters:
      update_rate: 100

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      drive_controller:
        type: diff_drive_controller/DiffDriveController
      imu_broadcaster:
        type: imu_sensor_broadcaster/IMUSensorBroadcaster
      twist_mux_controller:
        type: twist_mux_controller/TwistMuxController
      collision_monitor_controller:
        type: collision_monitor_controller/CollisionMonitor

  # IMU specification: https://www.phidgets.com/?tier=3&catid=10&pcid=8&prodid=1025#Tab_Specifications
  imu_broadcaster:
    ros__parameters:
      sensor_name: <namespace>/imu
      frame_id: <namespace>/imu_link
      # orientation_stddev: 4.3e-2 rad determined experimentally
      static_covariance_orientation: <static_covariance_orientation>
      # angular_velocity_stdev: 0.59 deg/s (0.01 rad/s) gyroscope white noise sigma, according to the manual
      static_covariance_angular_velocity: [1.0e-4, 0.0, 0.0, 0.0, 1.0e-4, 0.0, 0.0, 0.0, 1.0e-4]
      # linear_acceleration_stdev: 2.8 mg (0.0275 m/s^2) accelerometer white noise sigma, according to the manual
      static_covariance_linear_acceleration: [7.6e-4, 0.0, 0.0, 0.0, 7.6e-4, 0.0, 0.0, 0.0, 7.6e-4]

  drive_controller:
    ros__parameters:
      left_wheel_names: [fl_wheel_joint, rl_wheel_joint]
      right_wheel_names: [fr_wheel_joint, rr_wheel_joint]

      wheel_separation: 0.697
      wheel_radius: 0.1825

      # For skid drive kinematics it will act as ICR coefficient, kinematic model with ICR
      # coefficient isn't totally accurate and this coefficient can differ for various ground types
      wheel_separation_multiplier: 1.5

      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0

      publish_rate: 100.0
      odom_frame_id: odom
      base_frame_id: base_link
      twist_covariance_diagonal: [5.4e-5, 5.4e-5, 0.0, 0.0, 0.0, 1.9e-4] # Values measured experimentally

      # Whether to use feedback or commands for odometry calculations
      open_loop: false

      # Update odometry from velocity
      # in sensor fusion only velocity is used and with this setting it is more accurate
      position_feedback: false
      # velocity computation filtering
      velocity_rolling_window_size: 1

      enable_odom_tf: false

      cmd_vel_timeout: 0.2
      publish_limited_velocity: false

      # Velocity and acceleration limits
      linear:
        x:
          max_velocity: 2.0 # m/s
          min_velocity: -2.0 # m/s
          max_acceleration: 2.7 # m/s^2
          max_deceleration: -10.0 # m/s^2
          max_acceleration_reverse: -2.7 # m/s^2
          max_deceleration_reverse: 10.0 # m/s^2
          max_jerk: .NAN # m/s^3
          min_jerk: .NAN # m/s^3

      angular:
        z:
          max_velocity: 4.0 # rad/s
          min_velocity: -4.0 # rad/s
          max_acceleration: 5.74 # rad/s^2
          max_deceleration: -5.74 # rad/s^2
          max_acceleration_reverse: -5.74 # rad/s^2
          max_deceleration_reverse: 5.74 # rad/s^2
          max_jerk: .NAN # rad/s^3
          min_jerk: .NAN # rad/s^3

  twist_mux_controller:
    ros__parameters:
      holonomic: false
      cmd_vel_inputs:
        manual:
          topic: manual/cmd_vel
          timeout: 0.2
          priority: 100
        autonomous:
          topic: autonomous/cmd_vel
          timeout: 0.2
          priority: 10
        unknown:
          topic: cmd_vel
          timeout: 0.2
          priority: 1
      command_interface_linear_x: collision_monitor_controller/linear/x/velocity
      command_interface_angular_z: collision_monitor_controller/angular/z/velocity

  collision_monitor_controller:
    ros__parameters:
      enabled: True
      base_frame_id: <namespace>/base_link
      odom_frame_id: <namespace>/odom
      cmd_vel_in_topic: manual/cmd_vel
      cmd_vel_out_topic: cmd_vel_out
      state_topic: collision_monitor_state
      transform_tolerance: 0.5
      source_timeout: 5.0
      base_shift_correction: True
      stop_pub_timeout: 2.0
      enable_stamped_cmd_vel: True
      use_realtime_priority: false
      polygons: [VelocityPolygonStop, VelocityPolygonSlow]
      VelocityPolygonStop:
        type: velocity_polygon
        action_type: stop
        min_points: 6
        visualize: True
        enabled: True
        polygon_pub_topic: velocity_polygon_stop
        velocity_polygons: [rotation, translation_forward_slow, translation_forward, translation_backward_slow, translation_backward, stopped]
        holonomic: false
        rotation:
          points: "[[0.46, 0.48], [0.46, -0.48], [-0.46, -0.48], [-0.46, 0.48]]" # Adds 5cm to robot dimensions
          linear_min: -0.05
          linear_max: 0.05
          theta_min: -5.74
          theta_max: 5.74
        translation_forward_slow:
          points: "[[0.56, 0.48], [0.56, -0.48], [-0.22, -0.48], [-0.22, 0.48]]" # Adds 15cm to robot dimensions in direction of moving and 5cm on sides
          linear_min: 0.0
          linear_max: 0.5
          theta_min: -5.74
          theta_max: 5.74
        translation_forward:
          points: "[[0.71, 0.48], [0.71, -0.48], [-0.22, -0.48], [-0.22, 0.48]]" # Adds 30cm to robot dimensions in direction of moving and 5cm on sides
          linear_min: 0.5
          linear_max: 2.0
          theta_min: -5.74
          theta_max: 5.74
        translation_backward_slow:
          points: "[[0.22, 0.48], [0.22, -0.48], [-0.56, -0.48], [-0.56, 0.48]]" # Adds 15cm to robot dimensions in direction of moving and 5cm on sides
          linear_min: -0.5
          linear_max: 0.0
          theta_min: -5.74
          theta_max: 5.74
        translation_backward:
          points: "[[0.22, 0.48], [0.22, -0.48], [-0.71, -0.48], [-0.71, 0.48]]" # Adds 30cm to robot dimensions in direction of moving and 5cm on sides
          linear_min: -2.0
          linear_max: -0.5
          theta_min: -5.74
          theta_max: 5.74
        # # This is the last polygon to be checked, it should cover the entire range of robot's velocities
        # # It is used as the stopped polygon when the robot is not moving and as a fallback if the velocity
        # # is not covered by any of the other sub-polygons
        stopped:
          points: "[[0.46, 0.48], [0.46, -0.48], [-0.46, -0.48], [-0.46, 0.48]]" # Adds 5cm to robot dimensions
          linear_min: -2.0
          linear_max: 2.0
          theta_min: -5.74
          theta_max: 5.74
      VelocityPolygonSlow:
        type: velocity_polygon
        action_type: slowdown
        min_points: 6
        slowdown_ratio: 0.3
        visualize: True
        enabled: True
        polygon_pub_topic: velocity_polygon_slow
        velocity_polygons: [rotation, translation_forward_slow, translation_forward, translation_backward_slow, translation_backward, stopped]
        holonomic: false
        rotation:
          points: "[[0.56, 0.58], [0.56, -0.58], [-0.56, -0.58], [-0.56, 0.58]]" # Adds 15cm to robot dimensions
          linear_min: -0.05
          linear_max: 0.05
          theta_min: -5.74
          theta_max: 5.74
        translation_forward_slow:
          points: "[[0.76, 0.58], [0.76, -0.58], [-0.46, -0.58], [-0.46, 0.58]]" # Adds 30cm to robot dimensions in direction of moving and 15cm on sides
          linear_min: 0.0
          linear_max: 0.5
          theta_min: -5.74
          theta_max: 5.74
        translation_forward:
          points: "[[0.91, 0.58], [0.91, -0.58], [-0.46, -0.58], [-0.46, 0.58]]" # Adds 50cm to robot dimensions in direction of moving and 15cm on sides
          linear_min: 0.5
          linear_max: 2.0
          theta_min: -5.74
          theta_max: 5.74
        translation_backward_slow:
          points: "[[0.46, 0.58], [0.46, -0.58], [-0.76, -0.58], [-0.76, 0.58]]" # Adds 30cm to robot dimensions in direction of moving and 15cm on sides
          linear_min: -0.5
          linear_max: 0.0
          theta_min: -5.74
          theta_max: 5.74
        translation_backward:
          points: "[[0.46, 0.58], [0.46, -0.58], [-0.91, -0.58], [-0.91, 0.58]]" # Adds 50cm to robot dimensions in direction of moving and 15cm on sides
          linear_min: -2.0
          linear_max: -0.5
          theta_min: -5.74
          theta_max: 5.74
        # # This is the last polygon to be checked, it should cover the entire range of robot's velocities
        # # It is used as the stopped polygon when the robot is not moving and as a fallback if the velocity
        # # is not covered by any of the other sub-polygons
        stopped:
          points: "[[0.56, 0.58], [0.56, -0.58], [-0.56, -0.58], [-0.56, 0.58]]" # Adds 15cm to robot dimensions
          linear_min: -2.0
          linear_max: 2.0
          theta_min: -5.74
          theta_max: 5.74
      observation_sources: [scan]
      scan:
        source_timeout: 0.2
        type: scan
        topic: ~/scan
        enabled: False
